esphome:
  name: dev-rf-version2
#  includes:
#    - markisol.h  

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "UPDATE YOUR API KEY HERE"

ota:
  password: "UPDATE OTA PASSWORD HERE"

wifi:
  ssid: "WIFI SSID"
  password: "WIFI PASSWORD"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dev-Rf-Version2"
    password: "WvacsUf0Amkf"

captive_portal:

web_server:
  port: 80
  
sensor:
  - platform: wifi_signal
    name: Dev RF Bridge Wifi Signal
    update_interval: 10s
  - platform: uptime
    name: Dev RF Bridge Uptime

binary_sensor:
  - platform: status
    name: Dev RF Bridge Status

#switch:
#  - platform: template
#    name: "Blind Down"
#    turn_on_action:
#      lambda: sendMarkisolCommand("10111011111011111000100010000011110110101");
#  - platform: template
#    name: "Blind Up"
#    turn_on_action:
#      lambda: sendMarkisolCommand("10111011111011111000001110000011110101011");           
#  - platform: template
#    name: "Blind Stop"
#    turn_on_action:
#      lambda: sendMarkisolCommand("10111011111011111000101010000011110110001"); 
                  
  - platform: template
    name: "Fan On"
    turn_on_action:
      remote_transmitter.transmit_rc_switch_raw:
        code: '1010011001010110011001010101011001011001100110010110100110100110'
        protocol: 8  
        repeat:
          times: 10
          wait_time: 0ms                   
  - platform: template
    name: "Fan Off"
    turn_on_action:
      remote_transmitter.transmit_rc_switch_raw:
        code: '1010011001010110011001010101011001011001100110010110101010100110'
        protocol: 8  
        repeat:
          times: 10
          wait_time: 0ms    
  - platform: template
    name: "Hall Light on"
    turn_on_action:
      remote_transmitter.transmit_rc_switch_raw:
        code: '1010011001010110011010101010011001101001011001100110100101100110'
        protocol: 8  
        repeat:
          times: 10
          wait_time: 0ms                   
  - platform: template
    name: "Hall Light off"
    turn_on_action:
      remote_transmitter.transmit_rc_switch_raw:
        code: '1010011001010110011010101010011001101001011001100110101001100110'
        protocol: 8  
        repeat:
          times: 10
          wait_time: 0ms              
remote_receiver:
  pin: 13
  dump: rc_switch
  tolerance: 50%
  filter: 30us
  idle: 4ms
  buffer_size: 4kb

remote_transmitter:
  pin: 12
  carrier_duty_percent: 100%
